baseurl = "/"
languageCode = "pt-br"
title = "R Sociais"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
relativeurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	# General information
	author = "Curso de Programação para Ciências Sociais"
	description = "Material do Curso de Programação para Ciências Sociais"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/R4CS/site"

	version = ""
	logo = "logo_r4sc.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "R4CS"
	email   = "programacao.sociais@gmail.com"
	
[[menu.main]]
	name   = "Oficina SECS"
	url    = "secs/"
	weight = 1
	
[[menu.main]]
	name   = "Gráficos"
	url    = "ggplot2/"
	weight = 5
	
[[menu.main]]
	name   = "Mapas"
	url    = "mapas/"
	weight = 10
	
[[menu.main]]
	name   = "Web Scraping"
	url    = "webscraping/"
	weight = 15
	
[[menu.main]]
	name   = "Tutorial 1"
	url    = "tutorial1/"
	weight = 20

[[menu.main]]
	name   = "Tutorial 2"
	url    = "tutorial2/"
	weight = 25
	
[[menu.main]]
	name   = "Tutorial 3"
	url    = "tutorial3/"
	weight = 30

[[menu.main]]
	name   = "Tutorial 4"
	url    = "tutorial4/"
	weight = 35
	
[[menu.main]]
	name   = "Tutorial 5"
	url    = "tutorial5/"
	weight = 40

[[menu.main]]
	name   = "Tutorial 6"
	url    = "tutorial6/"
	weight = 45
	
[[menu.main]]
	name   = "Tutorial 7"
	url    = "tutorial7/"
	weight = 50
	
[[menu.main]]
	name   = "Tutorial 9"
	url    = "tutorial9/"
	weight = 55

[[menu.main]]
	name   = "Tutorial 10"
	url    = "tutorial10/"
	weight = 60
	
[[menu.main]]
	name   = "Tutorial 11"
	url    = "tutorial11/"
	weight = 65

[[menu.main]]
	name   = "Tutorial 12"
	url    = "tutorial12/"
	weight = 70
	
[[menu.main]]
	name   = "Tutorial 13"
	url    = "tutorial13/"
	weight = 75


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
